#!/usr/bin/env node
/*
 * Response headers for the built site.
 *
 * Cloudflare Pages reads a plain text file called _headers from the root of
 * what it serves. This writes that file after the build rather than keeping
 * it in public/, for one reason: the content security policy has to name the
 * exact inline scripts the site ships, and those are only known once the site
 * has been built. A hand-written list of hashes would be correct until the
 * next time somebody touched a script, and then it would silently stop the
 * page from working.
 *
 * The policy is deliberately strict, because this site can afford it. It has
 * no backend, no forms, no analytics, no third-party scripts and no code that
 * writes markup, so there is nothing here that needs a loophole.
 */
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { readdir } from 'node:fs/promises';
import { join } from 'node:path';

const OUT = 'dist';

/** Every built page, at any depth. */
async function pages(directory) {
  const found = [];
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    const path = join(directory, entry.name);
    if (entry.isDirectory()) found.push(...(await pages(path)));
    else if (entry.name.endsWith('.html')) found.push(path);
  }
  return found;
}

/*
 * A script tag with no src, which is the only kind the policy has to name.
 * Astro emits two of them: the theme, which is inline on purpose so that it
 * runs before the first paint, and the starfield, which is small enough that
 * the bundler leaves it in place.
 */
const INLINE_SCRIPT = /<script(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/g;

const files = await pages(OUT);
const hashes = new Set();

for (const file of files) {
  const html = readFileSync(file, 'utf8');
  for (const [, body] of html.matchAll(INLINE_SCRIPT)) {
    // The hash covers the script exactly as the browser receives it, so it is
    // taken from the raw text without trimming anything.
    hashes.add(`'sha256-${createHash('sha256').update(body, 'utf8').digest('base64')}'`);
  }
}

const policy = [
  // Nothing is allowed unless a line below says it is.
  `default-src 'none'`,
  // Bundled scripts, plus the exact inline ones this build produced.
  `script-src 'self' ${[...hashes].sort().join(' ')}`,
  /* Inline styles cannot be hashed: the colour of a saga arrives as a style
     attribute on the element that wears it, and there are hundreds per page.
     The narrower style-src-attr would express this better but is not carried
     everywhere, and where it is missing the fallback would strip every colour
     in the catalogue. */
  `style-src 'self' 'unsafe-inline'`,
  `img-src 'self'`,
  /* The fonts are self-hosted, but the bundler inlines the two smallest of
     them into the stylesheet as data URIs, so those two are not fetched from
     anywhere and a policy of 'self' alone silently drops them. Checked with
     the browser: without data: here, two of the typefaces never arrive. */
  `font-src 'self' data:`,
  // The site makes no requests of its own. Nothing to allow.
  `connect-src 'none'`,
  // There are no forms, so any form that appears is not ours.
  `form-action 'none'`,
  `frame-ancestors 'none'`,
  `base-uri 'none'`,
  `object-src 'none'`,
].join('; ');

/*
 * Comments stay above the rule rather than inside it. Every indented line in
 * a block is read as a header, and a parser that does not make an exception
 * for a comment would drop the header next to it without saying so.
 *
 * Referrer-Policy is no-referrer because the reader's place in the catalogue
 * is nobody else's business: following a citation out to a source should not
 * tell that source which entry they were reading.
 *
 * Permissions-Policy names capabilities the site never asks for. It is a list
 * of things that should stop working, not of things that should start.
 */
const headers = `# Generated by scripts/build-headers.mjs during the build.
# Do not edit here: edit the script, which is where the policy is written and
# where the inline script hashes are worked out from the built pages.

/*
  Content-Security-Policy: ${policy}
  X-Content-Type-Options: nosniff
  X-Frame-Options: DENY
  Referrer-Policy: no-referrer
  Cross-Origin-Opener-Policy: same-origin
  Permissions-Policy: accelerometer=(), camera=(), display-capture=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()
  Strict-Transport-Security: max-age=31536000
`;

writeFileSync(join(OUT, '_headers'), headers);

console.log(
  `Wrote ${OUT}/_headers. Content security policy names ${hashes.size} inline ` +
    `script(s) found across ${files.length} page(s).`,
);
