#!/usr/bin/env node
/*
 * A sitemap for the built site.
 *
 * This runs after the build rather than shipping a hand-written file, for the
 * same reason the headers do: the list of pages is only known once the site
 * has been built. A hand-maintained list would be right until somebody added
 * an entry, and then it would be quietly wrong.
 *
 * The one thing this file does that a plain list of URLs cannot is tell a
 * search engine that /en/timeline and /it/timeline are the same page in two
 * languages. Without that, the two compete with each other and the reader who
 * searched in Italian is as likely to be handed the English one.
 *
 * There is no lastmod. A date here is a claim about when a page last changed,
 * and the build has no honest way to know that: every file is written fresh
 * on every build, so the file's own timestamp would say "today" about an entry
 * nobody has touched in months. A missing field is better than a false one.
 */
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { join, sep } from 'node:path';
import languages from '../config/languages.json' with { type: 'json' };
import site from '../config/site.json' with { type: 'json' };

const OUT = 'dist';
const defaultLanguage = languages.find((language) => language.default) ?? languages[0];
const codes = new Set(languages.map((language) => language.code));

/** Every built page, at any depth. */
async function pages(directory) {
  const found = [];
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    const path = join(directory, entry.name);
    if (entry.isDirectory()) found.push(...(await pages(path)));
    else if (entry.name.endsWith('.html')) found.push(path);
  }
  return found;
}

/* XML has five characters that cannot appear as themselves. Every URL here is
   generated from ids the project controls, so this should never fire, but a
   sitemap that silently breaks on one entry is worse than one that escapes. */
function escapeXml(value) {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

const files = await pages(OUT);

/* Group the pages by what they are, rather than by where they live: the key
   is the path inside a language, so the same entry in every language lands in
   one group and can be emitted with its alternates. */
const groups = new Map();
let skipped = 0;

for (const file of files) {
  /* The build writes en/timeline.html rather than en/timeline/index.html, so
     the address is the path with the extension taken off. */
  const [code, ...rest] = file.split(sep).slice(1).join('/').replace(/\.html$/, '').split('/');
  if (!codes.has(code)) {
    /* Not a page of the catalogue: the root, which redirects to a language and
       says so with a canonical link, the not-found page, and any verification
       token a search engine asked to be served from the root. Offering any of
       them here would ask a crawler to index something that is not an entry. */
    skipped += 1;
    continue;
  }
  const path = rest.join('/');
  const group = groups.get(path) ?? new Map();
  group.set(code, `${site.url}/${[code, ...rest].join('/')}`);
  groups.set(path, group);
}

const entries = [];
for (const [, byLanguage] of [...groups].sort(([a], [b]) => a.localeCompare(b))) {
  const alternates = [...byLanguage].sort(([a], [b]) => a.localeCompare(b));
  /* x-default is what a search engine shows a reader whose language it cannot
     work out. It points at the source language, which is the one guaranteed
     to be complete. */
  const fallback = byLanguage.get(defaultLanguage.code);
  for (const [, url] of alternates) {
    const links = alternates.map(
      ([code, href]) =>
        `    <xhtml:link rel="alternate" hreflang="${code}" href="${escapeXml(href)}"/>`,
    );
    if (fallback) {
      links.push(
        `    <xhtml:link rel="alternate" hreflang="x-default" href="${escapeXml(fallback)}"/>`,
      );
    }
    entries.push(`  <url>\n    <loc>${escapeXml(url)}</loc>\n${links.join('\n')}\n  </url>`);
  }
}

const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/build-sitemap.mjs during the build. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:xhtml="http://www.w3.org/1999/xhtml">
${entries.join('\n')}
</urlset>
`;

await writeFile(join(OUT, 'sitemap.xml'), sitemap);

/* Tell crawlers where it is, from the same source as the URLs inside it. A
   sitemap nobody is pointed at is a file on a server. */
const robots = join(OUT, 'robots.txt');
const rules = await readFile(robots, 'utf8');
await writeFile(robots, `${rules.trimEnd()}\n\nSitemap: ${site.url}/sitemap.xml\n`);

console.log(
  `Wrote ${OUT}/sitemap.xml with ${entries.length} URL(s) across ` +
    `${groups.size} page(s) and ${languages.length} language(s). ` +
    `Skipped ${skipped} file(s) that are not language pages.`,
);
